version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017 RC
configuration: Release
before_build:
- ps: dotnet restore src
build_script:
- ps: >-
    cd src

    dotnet build

    dotnet pack
artifacts:
- path: 'bin\**\*.nupkg'
  name: NuGet Package
